package CenterInterfaceFE;

/**
* CenterInterfaceFE/InterfaceCenterHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from InterfaceMTL.idl
* Tuesday, August 1, 2017 10:00:22 PM EDT
*/

public final class InterfaceCenterHolder implements org.omg.CORBA.portable.Streamable
{
  public CenterInterfaceFE.InterfaceCenter value = null;

  public InterfaceCenterHolder ()
  {
  }

  public InterfaceCenterHolder (CenterInterfaceFE.InterfaceCenter initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CenterInterfaceFE.InterfaceCenterHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CenterInterfaceFE.InterfaceCenterHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CenterInterfaceFE.InterfaceCenterHelper.type ();
  }

}
