package CenterInterfaceFE;


/**
* CenterInterfaceFE/InterfaceCenter.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from InterfaceMTL.idl
* Tuesday, August 1, 2017 10:00:22 PM EDT
*/

public interface InterfaceCenter extends InterfaceCenterOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface InterfaceCenter
