package CenterInterfaceFE;


/**
* CenterInterfaceFE/InterfaceCenterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from InterfaceMTL.idl
* Wednesday, August 2, 2017 11:12:54 PM EDT
*/

public interface InterfaceCenterOperations 
{
  String createTRecord (String suc, String mi, String fn, String ln, String ad, String ph, String sp, String lo);
  String createSRecord (String suc, String mi, String fn, String ln, boolean s, String[] CourseRegistered);
  String getRecordCounts (String suc, String mi);
  String editRecord (String suc, String mi, String recordID, String fieldname, String[] newvalue);
  String MtransferRecord (String suc, String mid, String rid, String remoteName);
  void print (String mi);
} // interface InterfaceCenterOperations
