package CenterInterfaceFE;


/**
* CenterInterfaceFE/InterfaceCenter.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from InterfaceMTL.idl
* Wednesday, August 2, 2017 11:12:54 PM EDT
*/

public interface InterfaceCenter extends InterfaceCenterOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface InterfaceCenter
