package CenterInterfaceFE;


/**
* CenterInterfaceFE/InterfaceCenterPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from InterfaceMTL.idl
* Wednesday, August 2, 2017 11:12:54 PM EDT
*/

public abstract class InterfaceCenterPOA extends org.omg.PortableServer.Servant
 implements CenterInterfaceFE.InterfaceCenterOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("createTRecord", new java.lang.Integer (0));
    _methods.put ("createSRecord", new java.lang.Integer (1));
    _methods.put ("getRecordCounts", new java.lang.Integer (2));
    _methods.put ("editRecord", new java.lang.Integer (3));
    _methods.put ("MtransferRecord", new java.lang.Integer (4));
    _methods.put ("print", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CenterInterfaceFE/InterfaceCenter/createTRecord
       {
         String suc = in.read_string ();
         String mi = in.read_string ();
         String fn = in.read_string ();
         String ln = in.read_string ();
         String ad = in.read_string ();
         String ph = in.read_string ();
         String sp = in.read_string ();
         String lo = in.read_string ();
         String $result = null;
         $result = this.createTRecord (suc, mi, fn, ln, ad, ph, sp, lo);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // CenterInterfaceFE/InterfaceCenter/createSRecord
       {
         String suc = in.read_string ();
         String mi = in.read_string ();
         String fn = in.read_string ();
         String ln = in.read_string ();
         boolean s = in.read_boolean ();
         String CourseRegistered[] = CenterInterfaceFE.strHelper.read (in);
         String $result = null;
         $result = this.createSRecord (suc, mi, fn, ln, s, CourseRegistered);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // CenterInterfaceFE/InterfaceCenter/getRecordCounts
       {
         String suc = in.read_string ();
         String mi = in.read_string ();
         String $result = null;
         $result = this.getRecordCounts (suc, mi);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // CenterInterfaceFE/InterfaceCenter/editRecord
       {
         String suc = in.read_string ();
         String mi = in.read_string ();
         String recordID = in.read_string ();
         String fieldname = in.read_string ();
         String newvalue[] = CenterInterfaceFE.strHelper.read (in);
         String $result = null;
         $result = this.editRecord (suc, mi, recordID, fieldname, newvalue);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // CenterInterfaceFE/InterfaceCenter/MtransferRecord
       {
         String suc = in.read_string ();
         String mid = in.read_string ();
         String rid = in.read_string ();
         String remoteName = in.read_string ();
         String $result = null;
         $result = this.MtransferRecord (suc, mid, rid, remoteName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // CenterInterfaceFE/InterfaceCenter/print
       {
         String mi = in.read_string ();
         this.print (mi);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CenterInterfaceFE/InterfaceCenter:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public InterfaceCenter _this() 
  {
    return InterfaceCenterHelper.narrow(
    super._this_object());
  }

  public InterfaceCenter _this(org.omg.CORBA.ORB orb) 
  {
    return InterfaceCenterHelper.narrow(
    super._this_object(orb));
  }


} // class InterfaceCenterPOA
