package CenterInterface;


/**
* CenterInterface/InterfaceCenterHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from InterfaceMTL.idl
* Saturday, July 29, 2017 9:41:06 PM EDT
*/

abstract public class InterfaceCenterHelper
{
  private static String  _id = "IDL:CenterInterface/InterfaceCenter:1.0";

  public static void insert (org.omg.CORBA.Any a, CenterInterface.InterfaceCenter that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CenterInterface.InterfaceCenter extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (CenterInterface.InterfaceCenterHelper.id (), "InterfaceCenter");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CenterInterface.InterfaceCenter read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_InterfaceCenterStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CenterInterface.InterfaceCenter value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static CenterInterface.InterfaceCenter narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CenterInterface.InterfaceCenter)
      return (CenterInterface.InterfaceCenter)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CenterInterface._InterfaceCenterStub stub = new CenterInterface._InterfaceCenterStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static CenterInterface.InterfaceCenter unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CenterInterface.InterfaceCenter)
      return (CenterInterface.InterfaceCenter)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CenterInterface._InterfaceCenterStub stub = new CenterInterface._InterfaceCenterStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
