package CenterInterface;

/**
* CenterInterface/InterfaceCenterHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from InterfaceMTL.idl
* Saturday, July 29, 2017 9:41:06 PM EDT
*/

public final class InterfaceCenterHolder implements org.omg.CORBA.portable.Streamable
{
  public CenterInterface.InterfaceCenter value = null;

  public InterfaceCenterHolder ()
  {
  }

  public InterfaceCenterHolder (CenterInterface.InterfaceCenter initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CenterInterface.InterfaceCenterHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CenterInterface.InterfaceCenterHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CenterInterface.InterfaceCenterHelper.type ();
  }

}
